% Synthesizes raw ST Radar data from a prescribed wind profile
% and then runs the standard spectrum and moments processing pipeline.

headData = BeamHeader.empty(0, 5);
for i=1:5
	headData(i) = synth.create_synthetic_beamheader(...
		headerFields = struct("m_sCurrentBeamCnt", i - 1), ...
		altitudeRange="upper" ...
		);
end
h_start = headData(1).m_fWindow1StartHeight/1000;
h_end = headData(1).m_fWindow1EndHeight/1000;
nRangeBins = headData(1).m_sNumOfRangeBins;
[z, u, v, w] = synth.generate_wind_profile( ...
	nRangeBins   = nRangeBins, ...
	start_height = h_start,                       ...
	end_height   = h_end,                         ...
	sj_center    = rand() * 2 + 1,                ...
	tej_u        = rand() * 10 + 20,              ...
	tej_v        = rand() * 5 + 3,                ...
	tej_alt      = rand() * 5 + 12 ...
	);

obs = synth.create_synthetic_observation(...
	u, v, w,...
	SNR          = 10 .^ (linspace(50, -45, nRangeBins)/10), ...
	dc_rel_power = .1,                                     ...
	headerFields = headData,                                 ...
	bright_bands = struct(...
	"north", [[19, 15]; [20, 20]; [21, 8]; [40, 10]], ...
	"south", [[18, 15]; [19, 10];  [20, 8]; [40, 5]], ...
	"east", [[18, 10]; [19, 12]; [26, 8];], ...
	"west", [[18, 7]; [19, 12]; [25, 8];] ...
	) ...
	);
obs = obs.compute_spectra_with(@simple.compute_spectra);
obs = simple.HS_denoise_all_beams(obs);
obs = obs.compute_moments_with(@simple.compute_moments);

figure("Name", "Spectra");
tiledlayout(1,1)
for i = 1:1
	d = Data.directions(i);
	nexttile

	data = 10*log10(obs.(d).spectra);

	plt.plot_doppler_spectra(...
		spectra   = data,              ...
		direction = obs.(d).direction, ...
		ref_m     = obs.(d).ref_M1 * obs.DBS_Factor_V, ...
		comp_m    = obs.(d).M1 * obs.DBS_Factor_V, ...
		heights   = obs.heights,           ...
		x_max     = obs.v_max          ...
		)
	% plt.save_stacked_spectrogram(...
	% 	(data), ...
	% 	obs.heights, obs.velocities/1000, ...
	% 	plot_gradiated    = true,     ...
	% 	plot_add_colorbar = true,     ...
	% 	plot_color        = 'parula', ...
	% 	plot_thick        = 0.5,       ...
	% 	peak_marker       = "white.", ...
	% 	marker_size       = 0,        ...
	% 	amplitude_scale   = .9,       ...
	% 	ref_line_thick    = 0,       ...
	% 	ref_line_color    = "red",    ...
	% 	export_path       = 'plots/synth-0001-north-raw.png', ...
	% 	export_dpi        = 700 ...
	% 	);

end
% colorbar;
% %% UVW Wind Vector Plotting
return;
figure("Name", "UVW")

N = obs.north;
S = obs.south;
E = obs.east;
W = obs.west;
V = obs.vertical;

plt.plot_compared_M1((W.M1 - E.M1) * obs.DBS_Factor_H, obs.ref_U, 1, obs.heights, "Zonal (U)")
plt.plot_compared_M1((S.M1 - N.M1) * obs.DBS_Factor_H, obs.ref_V, 2, obs.heights, "Meridional (V)")
plt.plot_compared_M1(-V.M1 * obs.DBS_Factor_V, obs.ref_W, 3, obs.heights, "Vertical (W)")
