%%% Testing stacked spectrogram plotter using VisPy (sp_py)

filepath = fullfile("Data" , "rain", "EXP_DBS_CH4_28Jun2026_14_28_16");
disp("Processing file: " + filepath);

obs = Observation(filepath, add_mmts=false, add_uvw=false);
obs = utils.fill_spectras(obs, @mccf.compute_spectra);
% obs = simple.HS_denoise_all_beams(obs);

data = obs.north.denoised_spectra;
h_start = obs.north.start_height / 1000;
h_end = obs.north.end_height / 1000;
[h,x] = size(data);
x_ticks = linspace(-obs.v_max, obs.v_max, x);
y_ticks = linspace(h_start, h_end, h);

save_stacked_spectrogram(...
	(data), ...
	y_ticks, x_ticks, ...
	plot_gradiated    = true,     ...
	plot_add_colorbar = true,     ...
	plot_color        = 'parula', ...
	plot_thick        = 0.5,       ...
	peak_marker       = "white.", ...
	marker_size       = 0,        ...
	amplitude_scale   = .9,       ...
	ref_line_thick    = 0,       ...
	ref_line_color    = "red",    ...
	export_path       = 'plots/28Jun2026_14_28_16-north-raw.png', ...
	export_dpi        = 700 ...
);
