% This file was created to test if the raw file synthesizer is correctly creating the required raw file

filepath = fullfile("Data" , "other", "EXP_DBS_CH4_29Jul2026_16_23_15.raw");
disp("Processing file: " + filepath);

obs = Observation(filepath);
obs = obs.compute_spectra_with(@simple.compute_spectra);

u = obs.ref_U;
v = obs.ref_V;
w = obs.ref_W;

syn = synth.create_synthetic_observation(...
	u, v, w,...
	headerFields=[obs.north, obs.south, obs.east, obs.west, obs.vertical] ...
);

disp("Computing Spectra...");
syn = syn.compute_spectra_with(@mccf.compute_spectra);

for i = 1:5
	d = Data.directions(i);
	disp(d + ", raw: beam" + string(obs.(d).m_sCurrentBeamCnt) + " : az" + string(obs.(d).m_fAzimuth) + " : oz" + string(obs.(d).m_fOffZenith))
	disp(d + ", syn: beam" + string(syn.(d).m_sCurrentBeamCnt) + " : az" + string(syn.(d).m_fAzimuth) + " : oz" + string(syn.(d).m_fOffZenith))

	figure
	subplot(1, 2, 1);
	syn_d = syn.(d).spectra;
	obs_d = obs.(d).spectra;
	plt.plot_doppler_spectra(...
		spectra   = log10(obs_d),              ...
		ref_m     = obs.(d).ref_M1 * obs.DBS_Factor_V, ...
		direction = obs.(d).direction,                 ...
		heights   = syn.heights,                           ...
		x_max     = obs.v_max                          ...
		)
	subplot(1, 2, 2);
	plt.plot_doppler_spectra(...
		spectra   = log10(syn_d),              ...
		ref_m     = syn.(d).ref_M1 * obs.DBS_Factor_V, ...
		direction = syn.(d).direction,                 ...
		heights   = syn.heights,                           ...
		x_max     = syn.v_max                          ...
		)
end
