% Synthesizes raw ST Radar data from a prescribed wind profile
% and then runs the standard spectrum and moments processing pipeline.

nRangeBins = 173;
[z, u, v, w] = wind_synth.generate_wind_profile( ...
	nRangeBins=nRangeBins, ...
	start_height=3.15, ...
	end_height=20, ...
	sj_center=rand() * 2 + 1, ...
	tej_u = rand() * 10 + 20, ...
	tej_v = rand() * 5 + 3, ...
	tej_alt = rand() * 5 + 12 ...
);

vel_factor = 3.0e8 / 205e6 / 2.0;
DBS_Factor_V = vel_factor;
DBS_Factor_H = vel_factor / (2 * sind(10));

obs = utils.create_synthetic_observation(...
	u, v, w,...
	SNR  = 10 .^ (linspace(70, -30, nRangeBins)/10), ...
	dc_rel_power = .005, ...
	altitudeRange = "upper", ...
	bright_bands = struct(...
	"north", [[19, 15]; [20, 20]; [21, 8]; [40, 10]], ...
	"south", [[18, 15]; [19, 10];  [20, 8]; [40, 5]], ...
	"east", [[18, 10]; [19, 12]; [26, 8];], ...
	"west", [[18, 7]; [19, 12]; [25, 8];] ...
	) ...
);
obs = utils.fill_spectras(obs, @mccf.compute_spectra);
obs = simple.HS_denoise_all_beams(obs);
obs = utils.fill_moments(obs, @mccf.compute_moments);

N = obs.north;
S = obs.south;
E = obs.east;
W = obs.west;
V = obs.vertical;

%% Doppler Spectra and Moments Plotting

vmax = obs.v_max;
h_start = N.start_height / 1000;
h_end = N.end_height / 1000;

h = utils.compute_height_ranges(...
	h_start,...
	h_end,...
	N.m_sNumOfRangeBins ...
	);

l = ["north", "east", "west", "south", "vertical"];
h_start = obs.west.start_height / 1000;
h_end   = obs.west.end_height / 1000;
[y,x]   = size(obs.west.spectra);
y_ticks = linspace(h_start, h_end, y);
figure("Name", "Spectra");
pli = 1;
for i = 1:5
	d = l(i);
	subplot(1,5, pli);
	pli = pli+1;
	% already normalized
	obs_d = obs.(d).spectra;
	data = 10*log10(obs_d);
	% the imagesec plots things as it is and sets the xlim
	% since x limit is velocity (based on fd * DBS_V)
	% the moments must also be scaled by DBS_V
	utils.plot_doppler_spectra(...
		spectra   = data,              ...
		direction = obs.(d).direction, ...
		ref_m     = obs.(d).ref_M1 *  obs.DBS_Factor_V, ...
		comp_m    = obs.(d).M1 *  obs.DBS_Factor_V, ...
		heights   = y_ticks,           ...
		x_max     = obs.v_max          ...
		)
	% [h,x] = size(data);
	% x_ticks = linspace(-obs.v_max, obs.v_max, x);
	% y_ticks = linspace(h_start, h_end, h);

	% save_stacked_spectrogram(...
	% 	(data), ...
	% 	y_ticks, x_ticks, ...
	% 	plot_gradiated    = true,     ...
	% 	plot_add_colorbar = true,     ...
	% 	plot_color        = 'parula', ...
	% 	plot_thick        = 0.5,       ...
	% 	peak_marker       = "white.", ...
	% 	marker_size       = 0,        ...
	% 	amplitude_scale   = .9,       ...
	% 	ref_line_thick    = 0,       ...
	% 	ref_line_color    = "red",    ...
	% 	export_path       = 'plots/synth-0001-north-raw.png', ...
	% 	export_dpi        = 700 ...
	% 	);

end
% colorbar;
% %% UVW Wind Vector Plotting
figure("Name", "UVW")
utils.plot_compared_M1((W.M1 - E.M1) * obs.DBS_Factor_H, obs.ref_U, 1, h, "Zonal (U)")
utils.plot_compared_M1((S.M1 - N.M1) * obs.DBS_Factor_H, obs.ref_V, 2, h, "Meridional (V)")
utils.plot_compared_M1(-V.M1 * obs.DBS_Factor_V, obs.ref_W, 3, h, "Vertical (W)")
