%%% Testing the spectrogram plotter

filepath = fullfile("Data" , "other", "EXP_DBS_CH4_29Jul2026_16_23_15");
disp("Processing file: " + filepath);

obs = Observation(filepath);
obs = mccf.compute_all_spectra(obs);
% obs = simple.denoise_all_beams(obs);

data = obs.west.spectra;
h_start = obs.north.start_height / 1000;
h_end = obs.north.end_height / 1000;
[h,x] = size(data);
x_ticks = linspace(-obs.v_max, obs.v_max, x);
y_ticks = linspace(h_start, h_end, h);
stacked_spectrogram((data/max(data, [], 'all')), ...
	y_ticks, x_ticks, ...
	plot_gradiated    = true,     ...
	plot_add_colorbar = true,     ...
	plot_color        = 'parula', ...
	plot_thick        = .5,       ...
	peak_marker       = "white.", ...
	marker_size       = 0,        ...
	amplitude_scale   = .9,       ...
	ref_line_thick    = 0,       ...
	ref_line_color    = "red"...
	);

xlim([min(x_ticks), max(x_ticks)]);
ylim([min(y_ticks)-0.2, max(y_ticks)+0.4]);
