function [keys, vals] = get_beam_header_fields(b, config)
arguments (Input)
	b RadarData
	config.add_timestamp = false
	config.remove_ctrl_char = true
end
arguments (Output)
	keys cell
	vals cell
end

kv1 = {'m_sMagicNumber' 'm_sNumOfRangeBins' 'm_fBaudLength_us' 'm_sNFFT' 'm_sNumOfCohIntegrations' 'm_sNumOfInCohIntegrations' 'm_sCodeFlag' 'm_fIntrPulsePeriod_us' 'm_fPulseWidth_us' 'm_sNumOfObservWindows' 'm_sStationID' 'm_sReserved1' 'm_sReserved2' 'm_sReserved3', 'm_sReserved4'};
kts = {'m_sYear' 'm_sMonth' 'm_sDay' 'm_sHour' 'm_sMin' 'm_sSec'};
kv2 = {'m_fLatitude' 'm_fLongitude' 'm_fAltitude' 'm_fTotalPowerRadiated' 'm_fRadiatedPower_ClusterWise' 'm_sOperationMode' 'm_sCurrentBeamCnt' 'm_sTotalNumberofBeams' 'm_usCodeLength' 'm_cComment' 'm_fTRP_RF_Delay_us' 'm_fMGC_Gain_dB' 'm_usWindowType' 'm_usReserved' 'm_cArrRemarks' 'm_ulCodeA' 'm_ulCodeB' 'm_ucExperimentDataEnable' 'm_cReserved' 'm_fAzimuth' 'm_fOffZenith' 'm_fWindow1StartHeight' 'm_fWindow1EndHeight' 'm_fWindow2StartHeight' 'm_fWindow2EndHeight' 'm_fWindow3StartHeight' 'm_fWindow3EndHeight' 'm_fWindow4StartHeight' 'm_fWindow4EndHeight' 'm_fWindow5StartHeight' 'm_fWindow5EndHeight' };

vv1 = { ...
	b.m_sMagicNumber ...
	b.m_sNumOfRangeBins ...
	b.m_fBaudLength_us ...
	b.m_sNFFT ...
	b.m_sNumOfCohIntegrations ...
	b.m_sNumOfInCohIntegrations ...
	b.m_sCodeFlag ...
	b.m_fIntrPulsePeriod_us ...
	b.m_fPulseWidth_us ...
	b.m_sNumOfObservWindows ...
	b.m_sStationID ...
	b.m_sReserved1 ...
	b.m_sReserved2 ...
	b.m_sReserved3 ...
	b.m_sReserved4
	};
vts = {b.m_sYear b.m_sMonth b.m_sDay b.m_sHour b.m_sMin b.m_sSec};

comment = join(string(b.m_cComment), "");
arrRemarks = join(string(b.m_cArrRemarks), "");
if (config.remove_ctrl_char)
	comment = regexprep(comment, '[^\x20-\x7E]', '');
	arrRemarks = regexprep(arrRemarks, '[^\x20-\x7E]', '');
end
vv2 = {b.m_fLatitude ...
	b.m_fLongitude ...
	b.m_fAltitude ...
	b.m_fTotalPowerRadiated ...
	join(string(b.m_fRadiatedPower_ClusterWise), " ") ...
	b.m_sOperationMode ...
	b.m_sCurrentBeamCnt ...
	b.m_sTotalNumberofBeams ...
	b.m_usCodeLength ...
	comment ...
	b.m_fTRP_RF_Delay_us ...
	b.m_fMGC_Gain_dB ...
	b.m_usWindowType ...
	b.m_usReserved ...
	arrRemarks ...
	join(string(b.m_ulCodeA)) ...
	join(string(b.m_ulCodeB)) ...
	b.m_ucExperimentDataEnable ...
	join(string(b.m_cReserved)) ...
	b.m_fAzimuth ...
	b.m_fOffZenith ...
	b.m_fWindow1StartHeight ...
	b.m_fWindow1EndHeight ...
	b.m_fWindow2StartHeight ...
	b.m_fWindow2EndHeight ...
	b.m_fWindow3StartHeight ...
	b.m_fWindow3EndHeight ...
	b.m_fWindow4StartHeight ...
	b.m_fWindow4EndHeight ...
	b.m_fWindow5StartHeight ...
	b.m_fWindow5EndHeight ...
	};
if (config.add_timestamp)
	vals = [vv1, vts, vv2];
	keys = [kv1, kts, kv2];
else
	vals = [vv1, vv2];
	keys = [kv1, kv2];
end
