function [z, u, v, w] = generate_wind_profile(cfg)

arguments
	cfg.nRangeBins double = 173% [ ] number of range bins
	cfg.start_height double = 6.030 % [km] max height for which wind profile has to be generated
	cfg.end_height double = 32 % [km] max height for which wind profile has to be generated

	% Synoptic Background Profile
	cfg.bg_z0_m double = 0.05 % [m] Surface roughness length for terrain.
	cfg.bg_ustar double = 0.3 % [m/s] Friction velocity representing surface stress.
	cfg.bg_kappa double = 0.4 % [ ] von Kármán constant.
	cfg.bg_blh double = 1.5   % [km] boundary layer height

	% Low-Level Somali Jet - Onshore SW Monsoon flow
	cfg.sj_w double = 12       % [m/s] (zonal) onshore wind speeds of the SW monsoon jet
	cfg.sj_uv double = 14      % [m/s] (meridional) onshore wind speeds of the SW monsoon jet
	cfg.sj_center double = 1.5 % [km] Altitude of the jet core center.
	cfg.sj_s double = 0.8      % [km] Gaussian standard deviation controlling vertical thickness of the jet.

	% Tropical Easterly Jet (u_tej, v_tej)
	cfg.tej_u double = 35       % [m/s] (zonal) Strong easterly (westward) jet core speed near the tropopause.
	cfg.tej_v double = 3        % [m/s] (zonal) Strong easterly (westward) jet core speed near the tropopause.
	cfg.tej_alt double = 15.0   % [km] TEJ core altitude
	cfg.tej_vthick double = 2.5 % [km] TEJ core vertical layer thickness.

	% Stratospheric Quasi-Biennial Oscillation
	cfg.qbo_lambda double = 20 % [km] Vertical wavelength of alternating wind regimes in the stratosphere.
	cfg.qbo_u double = 8       % [m/s] Peak zonal amplitude of QBO phase shifts.
	cfg.qbo_v double = 3       % [m/s] Peak meridional amplitude of QBO phase shifts.
	cfg.qbo_alt double = 17    % [km] Altitude of QBO region

	% Orographic Updraft
	cfg.ou_alpha_slope double = atan(1.5 / 30.0); % [ ] Western Ghats ridge terrain slope (1.5 km height rise over 30 km distance).
	cfg.ou_H_lift double = 3.5;                   % [km] Vertical decay scale

	% Continuous Gravity Wave Spectrum
	cfg.gw_nmodes double = 20        % [ ] Number of continuous gravity wave spectrum modes
	cfg.gw_amp double = 2.5          % [m/s] Scaling factor for gravity wave horizontal velocity
	cfg.gw_max_lambda double = 4.0;  % [km] Upper limit for gravity wave vertical scale
	cfg.gw_damp_scale double = 12.0; % [km] Tightened damping scale (was 18.0 km) to control upper amplitude
	cfg.gw_cf double = 0.05          % [ ] Coupling factor deriving vertical wave speed from horizontal wave speed
	cfg.lw_Hs double = 7.0           % [km] Density scale height for wave amplification (e^(z / 2H_s))
	cfg.lw_N_bv double = 0.012;      % [rad/s] Brunt-Väisälä buoyancy frequency

	% Atmospheric Jitter & Thermal Convection
	cfg.jitter_amp double = 0.4    % [m/s] Amplitude of low-frequency spatial jet jitter
	cfg.plume_count double = 4     % [ ] Number of random convective updrafts/downdrafts
	cfg.plume_max_alt double = 6.0 % [km] Maximum altitude ceiling for thermal plumes

	% Kolmogorov Turbulence & Intermittency
	cfg.kt_vaf double = 0.25           % [ ] Vertical anisotropy scaling factor
	cfg.kt_bf double = 1               % [ ] Baseline factor for turbulence scaling
	cfg.kt_maxT double = 2.5           % [ ] Maximum turbulence boost under instability
	cfg.kt_Ric double = 0.25           % [ ] Critical Richardson Number Threshold
	cfg.kt_tlpeak double = 3           % [km] Turbulence layer peak altitude
	cfg.kt_vthick double = 2.5         % [km] Vertical thickness scale of turbulent layer
	cfg.turb_interm_sigma double = 0.5 % [ ] Intermittency parameter for log-normal weighting
end

% Height grid configuration (km)
h = linspace(cfg.start_height, cfg.end_height, cfg.nRangeBins);
N = length(h);

%% Synoptic Background Profile
u_bl = synth.synoptic_bg( ...
	h, ...
	bg_z0_m = cfg.bg_z0_m, ...
	bg_ustar = cfg.bg_ustar, ...
	bg_kappa = cfg.bg_kappa, ...
	bg_blh = cfg.bg_blh ...
	);

%% Low-Level Somali Jet
[u_llj, v_llj] = synth.somali_jet( ...
	h, ...
	sj_w = cfg.sj_w, ...
	sj_uv = cfg.sj_uv, ...
	sj_center = cfg.sj_center, ...
	sj_s = cfg.sj_s ...
	);

%% Tropical Easterly Jet
[u_tej, v_tej] = synth.tropical_easterly_jet( ...
	h, ...
	tej_u = cfg.tej_u, ...
	tej_v = cfg.tej_v, ...
	tej_alt = cfg.tej_alt, ...
	tej_vthick = cfg.tej_vthick ...
	);

%% Stratospheric QBO Regime
[u_qbo, v_qbo] = synth.stratospheric_qbo( ...
	h, ...
	qbo_lambda = cfg.qbo_lambda, ...
	qbo_u = cfg.qbo_u, ...
	qbo_v = cfg.qbo_v, ...
	qbo_alt = cfg.qbo_alt ...
	);

%%horizontal components with Spatial Jitter
u_mean = u_llj + u_bl + u_tej + u_qbo;
v_mean = v_llj + v_tej + v_qbo;

jitter_u = cfg.jitter_amp * (smoothdata(randn(N, 1), 'gaussian', 30))';
jitter_v = cfg.jitter_amp * (smoothdata(randn(N, 1), 'gaussian', 30))';
u_mean = u_mean + jitter_u;
v_mean = v_mean + jitter_v;

%% Orographic Updraft
w_oro = synth.orographic_updraft( ...
	h, ...
	u_mean, ...
	ou_alpha_slope = cfg.ou_alpha_slope, ...
	ou_H_lift = cfg.ou_H_lift ...
	);

%% Continuous Gravity Wave Spectrum
[u_gw, v_gw, w_gw] = synth.gravity_waves( ...
	h, ...
	gw_nmodes = cfg.gw_nmodes, ...
	gw_amp = cfg.gw_amp, ...
	gw_max_lambda = cfg.gw_max_lambda, ...
	gw_damp_scale = cfg.gw_damp_scale, ...
	gw_cf = cfg.gw_cf, ...
	lw_Hs = cfg.lw_Hs ...
	);

%% Random Convective Plumes in Lower Troposphere
w_plumes = synth.convective_plumes( ...
	h, ...
	plume_count = cfg.plume_count, ...
	plume_max_alt = cfg.plume_max_alt ...
	);

%% Stable Kolmogorov Turbulence with Log-Normal Intermittency
[u_turb, v_turb, w_turb] = synth.kolmogorov_turbulence( ...
	h, ...
	u_mean, ...
	v_mean, ...
	kt_vaf = cfg.kt_vaf, ...
	kt_bf = cfg.kt_bf, ...
	kt_maxT = cfg.kt_maxT, ...
	kt_Ric = cfg.kt_Ric, ...
	kt_tlpeak = cfg.kt_tlpeak, ...
	kt_vthick = cfg.kt_vthick, ...
	turb_interm_sigma = cfg.turb_interm_sigma, ...
	lw_N_bv = cfg.lw_N_bv ...
	);

%%3D Wind Vector Assembly
z = h';
u = (u_mean + u_gw + u_turb)';
v = (v_mean + v_gw + v_turb)';
w = (w_oro + w_gw + w_plumes + w_turb)';
end
